name: Snapshot Build
on:
  push:
    branches:
      release-from-snapshot
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_windows:
    name: Build (Windows)
    if: github.repository == 'jordigh/cc65'
    runs-on: windows-latest

    steps:
      - shell: bash
        run: git config --global core.autocrlf input

      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app (debug)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Debug

      - name: Build app (release)
        run: msbuild src\cc65.sln -t:rebuild -property:Configuration=Release

  build_linux:
    name: Build, Test, and Snapshot (Linux)
    if: github.repository == 'jordigh/cc65'
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install linuxdoc-tools-info gcc-mingw-w64-x86-64 gcc-mingw-w64-i686

      - shell: bash
        run: git config --global core.autocrlf input
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Do some simple style checks
        shell: bash
        run: make -j2 checkstyle
      - name: Check bsearch tables
        shell: bash
        run: make -j2 sorted
      - name: Build the tools.
        shell: bash
        run: |
            make -j2 bin USER_CFLAGS=-Werror  QUIET=1
            make -j2 util QUIET=1
      - name: Build the platform libraries.
        shell: bash
        run: make -j2 lib QUIET=1
      - name: Run the regression tests.
        shell: bash
        run: make -j2 test QUIET=1
      - name: Test that the samples can be built.
        shell: bash
        run: make -j2 samples QUIET=1
      - name: Remove the output from the samples tests.
        shell: bash
        run: make -C samples clean QUIET=1
      - name: Remove programs in util directory
        shell: bash
        run: make -C util clean QUIET=1
      - name: Build the document files.
        shell: bash
        run: make -j2 doc QUIET=1
      - name: Build and package 64-bit Windows versions of the tools.
        run: |
          make -C src clean QUIET=1
          make -j2 bin QUIET=1 USER_CFLAGS=-Werror CROSS_COMPILE=x86_64-w64-mingw32-
          make zip
          mv cc65.zip cc65-snapshot-win64.zip
      - name: Build and package 32-bit Windows versions of the tools.
        run: |
          make -C src clean QUIET=1
          make -j2 bin USER_CFLAGS=-Werror QUIET=1 CROSS_COMPILE=i686-w64-mingw32-
          make zip
          mv cc65.zip cc65-snapshot-win32.zip

      - name: Upload a 32-bit Snapshot Zip
        uses: actions/upload-artifact@v4
        with:
          name: cc65-snapshot-win32
          path: cc65-snapshot-win32.zip
          retention-days: 90
      - name: Upload a 64-bit Snapshot Zip
        uses: actions/upload-artifact@v4
        with:
          name: cc65-snapshot-win64
          path: cc65-snapshot-win64.zip
          retention-days: 90

      - name: Package offline documents.
        run: 7z a cc65-snapshot-docs.zip ./html/*.*
      - name: Upload a Documents Snapshot Zip
        uses: actions/upload-artifact@v4
        with:
          name: cc65-snapshot-docs
          path: cc65-snapshot-docs.zip
          retention-days: 90

